# Tomcat
server:
  port: 9527



spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      routes:
        - id: payment_one #路由id，没有固定的名称规则要求唯一，建议配合服务名使用
          #uri: http://localhost:8001 #匹配后提供的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/get/**  #断言，路径匹配进行路由
        - id: payment_one #路由id，没有固定的名称规则要求唯一，建议配合服务名使用
          #uri: http://localhost:8001 #匹配后提供的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/lb/**  #断言，路径匹配进行路由
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true #向注册中心注册自己
    fetch-registry: true  #是否从eurekaServer中抓取数据，单节点无所谓，集群必须要是true这样才能配合队列的负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

logging:
  level:
    com:
      guigu:
        springcloud: debug
